-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tbl_job_application
(
    id integer NOT NULL DEFAULT nextval('applications_applicationid_seq'::regclass),
    job_id integer,
    job_seeker_id integer,
    resume_file_path character varying(255) COLLATE pg_catalog."default" NOT NULL,
    cover_letter text COLLATE pg_catalog."default",
    date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tbl_job_application PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tbl_job_post
(
    id integer NOT NULL DEFAULT nextval('joblistings_jobid_seq'::regclass),
    employer_id integer,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    requirements text COLLATE pg_catalog."default",
    location character varying(255) COLLATE pg_catalog."default" NOT NULL,
    industry character varying(20) COLLATE pg_catalog."default",
    job_type character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT pk_tbl_job_post PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tbl_user
(
    id integer NOT NULL DEFAULT nextval('users_userid_seq'::regclass),
    user_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    salt character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_tbl_user PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.tbl_job_application
    ADD CONSTRAINT fk_job_id FOREIGN KEY (job_id)
    REFERENCES public.tbl_job_post (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tbl_job_application
    ADD CONSTRAINT fk_jobseeker_id FOREIGN KEY (job_seeker_id)
    REFERENCES public.tbl_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tbl_job_post
    ADD CONSTRAINT fk_employer_id FOREIGN KEY (employer_id)
    REFERENCES public.tbl_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;