openapi: 3.0.0
info:
  version: 1.0.0
  title: Job Edit API
  description: API for editing job descriptions by employers

paths:
  /api/edit-job-description/employer/{employerId}/{jobId}:
    put:
      summary: Update job description
      description: Updates the job description for a specific job by the employer.
      parameters:
        - in: path
          name: employerId
          required: true
          description: Employer ID
          schema:
            type: integer
        - in: path
          name: jobId
          required: true
          description: Job ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                description:
                  type: string
                  description: New job description
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Operation status
                  message:
                    type: string
                    description: Operation message
        '400':
          description: Invalid input format or URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
        '403':
          description: Job not mapped to the employer
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error status
                  message:
                    type: string
                    description: Error message
